'use strict';
const $=id=>document.getElementById(id),E=Scrap,icons={plus:'M12 5v14M5 12h14',close:'m6 6 12 12M6 18 18 6',pen:'m16 3 5 5-12 12-6 1 1-6Z M14 5l5 5',undo:'M3 10h10a7 7 0 0 1 0 14 M3 10l5-5M3 10l5 5',redo:'M21 10H11a7 7 0 0 0 0 14 M21 10l-5-5M21 10l-5 5',folder:'M3 7h7l2 3h9v11H3Z M3 7V4h7l2 3h9v3',export:'M14 3h7v7M21 3 10 14M10 4H4v17h17v-6',template:'M4 3h16v18H4ZM4 10h16M11 10v11',image:'M3 4h18v16H3Z M3 16l5-6 5 5 3-3 5 5 M15 8h.01',text:'M4 4h16M12 4v16M8 20h8',star:'m12 2 3 7 7 1-5 5 1 7-6-4-6 4 1-7-5-5 7-1Z',layers:'m12 3 10 6-10 6L2 9Z M2 14l10 6 10-6 M2 18l10 6 10-6',history:'M3 11a9 9 0 1 1 2 7 M3 4v7h7 M12 7v6l4 3',search:'M15 15l6 6 M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0',copy:'M8 8h13v13H8ZM3 16V3h13',trash:'M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7',front:'M3 3h13v13H3ZM8 20h13V8',fit:'M3 9V3h6M15 3h6v6M21 15v6h-6M9 21H3v-6',sliders:'M3 6h18M3 12h18M3 18h18M8 3v6M16 9v6M9 15v6',alignLeft:'M3 4h18M3 9h12M3 14h18M3 19h12',alignCenter:'M3 4h18M6 9h12M3 14h18M6 19h12',alignRight:'M3 4h18M9 9h12M3 14h18M9 19h12',up:'m6 14 6-6 6 6',down:'m6 10 6 6 6-6',lock:'M6 10h12v11H6ZM8 10V6a4 4 0 0 1 8 0v4',eye:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0',eyeOff:'M3 3l18 18M2 12s4-7 10-7c6 0 10 7 10 7s-4 7-10 7S2 12 2 12',download:'M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4'};
function icon(name){return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="'+(icons[name]||icons.star)+'"/></svg>'}document.querySelectorAll('[data-icon]').forEach(e=>e.innerHTML=icon(e.dataset.icon));
const info={spark:['반짝임','point','#e95b25'],star:['별','point','#f2cd30'],heart:['하트','point','#d43a36'],arrow:['낙서 화살표','point','#252729'],tape:['테이프','paper','#b0c8df'],ticket:['티켓','paper','#eee1bd'],scribble:['밑줄','point','#252729'],oval:['동그라미','point','#d43a36'],checker:['체크 조각','paper','#252729'],flower:['꽃','point','#e8ba46'],smile:['스마일','point','#f1cd3a'],seal:['스탬프','paper','#e5bf67']};const colors=['#252729','#e95b25','#cf3934','#f5efe1','#f4cd34','#3d7356'];const frameNames={none:'기본',torn:'찢어진 종이',polaroid:'폴라로이드',rounded:'둥근 모서리'},effectNames={plain:'기본',outline:'외곽선',shadow:'그림자',label:'라벨'},patternNames={paper:'종이 질감',plain:'단색',grid:'모눈',dots:'도트',checker:'체크'};
let state=E.preset(0),selected=state.layers.find(n=>n.type==='text').id,images={},templates=[],templateId=null,ready=false,busy=false,undoStack=[],redoStack=[],viewScale=1,drag=null,draftTimer=null,currentPanel='stickers',filter='all',storeDB=null,saveSeq=0;
const current=()=>state.layers.find(n=>n.id===selected),note=(msg,error=false)=>{$('status').textContent=msg;$('status').classList.toggle('error',error);if($('savedDialog').open){$('dialogStatus').textContent=msg;$('dialogStatus').classList.toggle('error',error)}};
function setBusy(v){busy=v;document.body.classList.toggle('busy',v);$('download').disabled=v}
function capture(){return JSON.stringify(state)}function remember(old){if(old===capture())return;undoStack.push(old);let bytes=undoStack.reduce((n,s)=>n+s.length,0);while(undoStack.length>35||bytes>24000000&&undoStack.length>1)bytes-=undoStack.shift().length;redoStack=[];}
function mutate(action){if(!ready||busy)return;const old=capture();try{action();state=E.valid(state);remember(old);refresh();scheduleDraft()}catch(e){state=JSON.parse(old);refresh();note(e.message+' 기존 작업은 유지됩니다.',true)}}
function choose(id){selected=id;refresh(false)}
function modify(props){const n=current();if(!n)return;if(n.locked){note('잠금을 해제하면 편집할 수 있어요.');return}mutate(()=>Object.assign(current(),props))}
function add(n){if(state.layers.length>=40){note('레이어는 최대 40개까지 추가할 수 있어요.',true);return}mutate(()=>{state.layers.push(n);selected=n.id})}
function remove(){const n=current();if(!n)return;if(n.locked){note('잠긴 레이어예요. 먼저 잠금을 해제하세요.');return}mutate(()=>{state.layers=state.layers.filter(x=>x.id!==selected);selected=null})}
function duplicate(){const n=current();if(!n)return;add({...E.clone(n),id:E.id(),x:Math.min(95,n.x+3),y:Math.min(95,n.y+3),locked:false})}
function reorder(dir){if(!current())return;mutate(()=>{const i=state.layers.findIndex(n=>n.id===selected),j=dir===99?state.layers.length-1:Math.max(0,Math.min(state.layers.length-1,i+dir));const [n]=state.layers.splice(i,1);state.layers.splice(j,0,n)})}
function undo(){if(busy||!undoStack.length)return;redoStack.push(capture());state=JSON.parse(undoStack.pop());if(!current())selected=null;refresh();scheduleDraft()}
function redo(){if(busy||!redoStack.length)return;undoStack.push(capture());state=JSON.parse(redoStack.pop());if(!current())selected=null;refresh();scheduleDraft()}
function val(id,v){if(document.activeElement!==$(id))$(id).value=v}
function refresh(redraw=true){val('title',state.title);$('dimensions').textContent=E.sizes[state.ratio].join(' × ');document.querySelectorAll('[data-ratio]').forEach(b=>{b.classList.toggle('active',state.ratio===b.dataset.ratio);b.setAttribute('aria-pressed',state.ratio===b.dataset.ratio)});$('undo').disabled=!undoStack.length;$('redo').disabled=!redoStack.length;if(redraw)E.render($('canvas'),state,images);fit();drawOverlay();properties();layerList();}
function properties(){const n=current();$('noSelection').hidden=!!n;$('objectSettings').hidden=!n;$('propertyTitle').textContent=n?{text:'문구 스타일',image:'사진 스타일',sticker:'스티커 스타일'}[n.type]:'요소 설정';$('selectedType').textContent=n?(n.locked?'잠긴 요소':{text:'Aa 문구',image:'사진',sticker:'스티커'}[n.type]):'요소 선택';for(const k of ['duplicate','remove','front','up','down','lock'])$(k).disabled=!n;val('bg',state.bg);document.querySelectorAll('#backgroundPalette button').forEach(b=>b.classList.toggle('active',b.dataset.color===state.bg));document.querySelectorAll('[data-pattern]').forEach(b=>b.classList.toggle('active',b.dataset.pattern===state.pattern));if(!n)return;$('textSettings').hidden=n.type!=='text';$('imageSettings').hidden=n.type!=='image';$('colorSettings').hidden=n.type==='image';for(const k of ['x','y','w','h','rotation','opacity'])val(k,Math.round(n[k]*10)/10);$('rotationValue').textContent=Math.round(n.rotation)+'°';$('opacityValue').textContent=Math.round(n.opacity)+'%';$('lock').classList.toggle('active',n.locked);if(n.type!=='image'){val('color',n.color);document.querySelectorAll('#palette button').forEach(b=>b.classList.toggle('active',b.dataset.color===n.color));}if(n.type==='text'){for(const k of ['text','font','size'])val(k,n[k]);$('textCount').textContent=n.text.length+' / 2,000';document.querySelectorAll('[data-align]').forEach(b=>b.classList.toggle('active',n.align===b.dataset.align));document.querySelectorAll('[data-effect]').forEach(b=>b.classList.toggle('active',n.effect===b.dataset.effect));}if(n.type==='image'){val('imageZoom',n.zoom);val('cropX',n.cropX);val('cropY',n.cropY);document.querySelectorAll('[data-frame]').forEach(b=>b.classList.toggle('active',n.frame===b.dataset.frame));}}
function fit(){const [W,H]=E.sizes[state.ratio],stage=$('stage'),scale=Math.max(.08,Math.min((stage.clientWidth-30)/W,(stage.clientHeight-32)/H))*viewScale;$('canvasWrap').style.width=(W*scale)+'px';$('canvasWrap').style.height=(H*scale)+'px';$('viewZoom').textContent=Math.round(scale*100)+'%'}
function drawOverlay(){const cv=$('overlay'),[W,H]=E.sizes[state.ratio];cv.width=W;cv.height=H;const c=cv.getContext('2d'),n=current();if(!n||n.hidden)return;const scale=$('canvasWrap').clientWidth/W||.5,w=W*n.w/100,h=H*n.h/100,line=1.3/scale,knob=4/scale,arm=24/scale;c.save();c.translate(W*n.x/100,H*n.y/100);c.rotate(n.rotation*Math.PI/180);c.strokeStyle=n.locked?'#939ba9':'#e95b25';c.lineWidth=line;c.strokeRect(-w/2,-h/2,w,h);if(!n.locked){c.fillStyle='#fff';for(const x of [-w/2,w/2])for(const y of [-h/2,h/2]){c.beginPath();c.arc(x,y,knob,0,Math.PI*2);c.fill();c.stroke();}c.beginPath();c.moveTo(0,-h/2);c.lineTo(0,-h/2-arm);c.stroke();c.beginPath();c.arc(0,-h/2-arm,knob*1.2,0,Math.PI*2);c.fill();c.stroke();}c.restore();}
function thumb(n){const cv=document.createElement('canvas');cv.width=80;cv.height=80;const c=cv.getContext('2d');if(n.type==='image'&&images[n.src]){const im=images[n.src],r=Math.max(80/im.width,80/im.height);c.drawImage(im,(80-im.width*r)/2,(80-im.height*r)/2,im.width*r,im.height*r);}else if(n.type==='sticker'){c.translate(40,40);E.sticker(c,n,65,65);}else{c.fillStyle=n.color;c.font='48px CardSans';c.textAlign='center';c.fillText('T',40,59);}cv.className='thumb';return cv;}
function layerList(){const parent=$('layers');const scroll=parent.scrollTop;parent.replaceChildren();$('layerCount').textContent=state.layers.length;for(const n of [...state.layers].reverse()){const row=document.createElement('div');row.className='layer-row'+(n.id===selected?' active':'')+(n.hidden?' hidden-layer':'');row.tabIndex=0;row.setAttribute('role','button');row.setAttribute('aria-label',(n.type==='text'?n.text.slice(0,30):n.type==='image'?'사진':info[n.kind][0])+' 레이어 선택');row.onclick=()=>choose(n.id);row.onkeydown=e=>{if(e.target!==row)return;if(e.key==='Enter'||e.key===' '){e.preventDefault();choose(n.id)}};const eye=document.createElement('button');eye.className='eye';eye.innerHTML=icon(n.hidden?'eyeOff':'eye');eye.setAttribute('aria-label',n.hidden?'레이어 보이기':'레이어 숨기기');eye.onclick=e=>{e.stopPropagation();mutate(()=>n.hidden=!n.hidden)};const label=document.createElement('span');label.className='label';label.textContent=n.type==='text'?(n.text.replaceAll('\n',' ')||'빈 문구'):n.type==='image'?'사진 · '+frameNames[n.frame]:info[n.kind][0];row.append(eye,thumb(n),label);if(n.locked){const l=document.createElement('span');l.innerHTML=icon('lock');l.className='layer-lock';row.append(l)}parent.append(row);}parent.scrollTop=scroll;}
function panel(name){currentPanel=name;document.querySelectorAll('.tool-panel').forEach(p=>p.hidden=p.id!=='panel-'+name);document.querySelectorAll('[data-panel]').forEach(b=>b.classList.toggle('active',b.dataset.panel===name));$('panelTitle').textContent={stickers:'취향대로 붙여봐',templates:'한 장의 시작',photos:'사진으로 채워봐',text:'마음을 한 줄로',background:'바탕부터 다르게'}[name];if(matchMedia('(max-width:650px)').matches){document.body.classList.toggle('assets-open',true);document.body.classList.toggle('properties-open',false);}}
function buildStickers(){const grid=$('stickerGrid');grid.replaceChildren();const q=$('search').value.trim();for(const kind of E.stickers){const [name,cat,col]=info[kind];if((filter!=='all'&&cat!==filter)||(q&&!name.includes(q)))continue;const b=document.createElement('button');b.className='sticker-tile';b.setAttribute('aria-label',name+' 추가');b.title=name+' 추가';const cv=document.createElement('canvas');cv.width=150;cv.height=150;const c=cv.getContext('2d');c.translate(75,75);E.sticker(c,{kind,color:col},kind==='tape'?125:105,kind==='tape'?45:kind==='scribble'?65:105);const label=document.createElement('span');label.textContent=name;b.append(cv,label);b.onclick=()=>{add(E.node('sticker',{kind,color:col,w:kind==='tape'?28:22,h:kind==='tape'?6:18}));note(name+'을 붙였어요. 카드 위에서 움직여보세요.');};grid.append(b)}if(!grid.children.length){const p=document.createElement('p');p.className='muted';p.textContent='일치하는 요소가 없어요.';grid.append(p)}}
async function usePreset(i){if(busy||!ready)return;const yes=await confirmAction('새 분위기로 바꿀까요?','현재 작업은 바뀌지만 실행 취소로 돌아올 수 있어요. 저장한 템플릿은 유지됩니다.');if(!yes)return;mutate(()=>{state=E.preset(i);selected=state.layers.find(n=>n.type==='text')?.id;templateId=null});note('새 템플릿을 적용했어요.')}
function renderMini(cv,s){E.render(cv,s,images);const tmp=document.createElement('canvas');tmp.width=180;tmp.height=Math.round(180*cv.height/cv.width);tmp.getContext('2d').drawImage(cv,0,0,tmp.width,tmp.height);cv.width=tmp.width;cv.height=tmp.height;cv.getContext('2d').drawImage(tmp,0,0);}
function buildPresets(){for(const pid of ['miniPresets','presetGrid']){$(pid).replaceChildren();for(let i=0;i<(pid==='miniPresets'?4:6);i++){const s=E.preset(i),b=document.createElement('button'),cv=document.createElement('canvas'),l=document.createElement('span');renderMini(cv,s);b.className='preset-card';b.title=s.title;l.textContent=s.title;b.append(cv,l);b.onclick=()=>usePreset(i);$(pid).append(b)}}}
function buildTools(){for(const pid of ['palette','backgroundPalette'])for(const color of [...colors,...(pid==='backgroundPalette'?['#f7c8d3','#dce9fa','#eff0db']:[])]){const b=document.createElement('button');b.style.setProperty('--color',color);b.dataset.color=color;b.setAttribute('aria-label',color+' 색상');b.onclick=()=>pid==='palette'?modify({color}):mutate(()=>state.bg=color);$(pid).append(b)}for(const pid of ['effects','assetEffects'])for(const [effect,name]of Object.entries(effectNames)){const b=document.createElement('button');b.dataset.effect=effect;b.innerHTML='<b>가나다</b><span>'+name+'</span>';b.onclick=()=>{if(current()?.type==='text')modify({effect});else note('먼저 문구를 선택하세요.')};$(pid).append(b)}for(const pid of ['frames','assetFrames'])for(const [frame,name]of Object.entries(frameNames)){const b=document.createElement('button');b.dataset.frame=frame;b.innerHTML='<span class="frame-preview '+frame+'"></span><span>'+name+'</span>';b.onclick=()=>{if(current()?.type==='image')modify({frame});else note('카드에서 사진을 선택한 뒤 프레임을 적용하세요.')};$(pid).append(b)}for(const [pattern,name]of Object.entries(patternNames)){const b=document.createElement('button'),c=document.createElement('canvas'),l=document.createElement('span');b.dataset.pattern=pattern;E.render(c,{...E.base(),ratio:'1:1',pattern},{});l.textContent=name;b.append(c,l);b.onclick=()=>mutate(()=>state.pattern=pattern);$('patterns').append(b)}}
function confirmAction(title,message){return new Promise(resolve=>{const d=$('confirmDialog');$('confirmTitle').textContent=title;$('confirmMessage').textContent=message;let done=false;const end=v=>{if(done)return;done=true;d.close();resolve(v)};$('confirmYes').onclick=()=>end(true);$('confirmNo').onclick=()=>end(false);d.oncancel=e=>{e.preventDefault();end(false)};d.showModal()})}
async function decode(src){if(images[src])return images[src];const im=new Image();im.src=src;await im.decode();if(!im.width||!im.height||im.width*im.height>20000000)throw Error('이미지는 2,000만 화소 이내여야 합니다.');return im;}
async function prepare(s){const next={...images};for(const n of s.layers)if(n.type==='image'&&!next[n.src])next[n.src]=await decode(n.src);return next;}
function openDB(){return new Promise((res,rej)=>{const req=indexedDB.open('one-card-studio-v2',1);req.onupgradeneeded=()=>req.result.createObjectStore('data');req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error);req.onblocked=()=>rej(Error('다른 탭에서 저장소를 사용 중입니다.'));})}
function readDB(key){return new Promise((res,rej)=>{const q=storeDB.transaction('data').objectStore('data').get(key);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
function writeDB(key,value){return new Promise((res,rej)=>{if(!storeDB)return rej(Error('브라우저 저장소를 사용할 수 없습니다.'));let tx;try{tx=storeDB.transaction('data','readwrite');tx.objectStore('data').put(value,key)}catch(e){rej(e);return}tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error);tx.onabort=()=>rej(tx.error||Error('저장이 중단되었습니다.'))})}
function scheduleDraft(){clearTimeout(draftTimer);$('autosave').textContent='저장 중…';const seq=++saveSeq;draftTimer=setTimeout(async()=>{try{const raw=capture();if(raw.length>16000000)throw Error('현재 카드가 너무 큽니다.');await writeDB('draft',JSON.parse(raw));if(seq===saveSeq)$('autosave').textContent='이 기기에 저장됨';}catch(e){$('autosave').textContent='자동 저장 실패';note('자동 저장을 못 했어요. 템플릿 JSON이나 이미지를 내려받아 보관하세요.',true)}},350)}
async function storeTemplates(next){const raw=JSON.stringify({version:2,templates:next});if(raw.length>26000000)throw Error('백업 용량 26MB를 초과했습니다. 템플릿이나 사진을 줄여주세요.');await writeDB('templates',next);templates=next;renderSaved();}
function openSaved(){if(!ready||busy)return;$('dialogStatus').textContent='';$('templateName').value=templateId?templates.find(t=>t.id===templateId)?.name||state.title:state.title;renderSaved();$('savedDialog').showModal()}
function renderSaved(){const list=$('savedList');list.replaceChildren();$('updateTemplate').disabled=!templateId||!templates.some(t=>t.id===templateId);if(!templates.length){const p=document.createElement('p');p.className='empty-state';p.textContent='아직 저장한 템플릿이 없어요. 지금 만든 한 장부터 모아보세요.';list.append(p)}for(const t of templates){const row=document.createElement('div');row.className='saved-item'+(templateId===t.id?' selected':'');const cv=document.createElement('canvas');renderMini(cv,t.state);const b=document.createElement('button');b.className='saved-name';b.textContent=t.name;const sm=document.createElement('small');sm.textContent=t.state.ratio+' · '+t.state.layers.length+'개 요소 · 불러오기';b.append(sm);b.onclick=async()=>{if(busy)return;setBusy(true);try{const n=E.valid(t.state),im=await prepare(n),old=capture();state=n;images=im;templateId=t.id;selected=state.layers.find(n=>n.type==='text')?.id||null;remember(old);refresh();scheduleDraft();$('savedDialog').close();note('“'+t.name+'”을 불러왔어요.')}catch(e){note('불러오기 실패: '+e.message+' 기존 작업은 유지됩니다.',true)}finally{setBusy(false)}};const del=document.createElement('button');del.className='icon-button';del.innerHTML=icon('trash');del.setAttribute('aria-label',t.name+' 삭제');del.onclick=async()=>{if(busy)return;const yes=await confirmAction('템플릿을 삭제할까요?','“'+t.name+'”을 목록에서 삭제합니다. 현재 편집 중인 카드는 유지됩니다.');if(!yes)return;try{await storeTemplates(templates.filter(x=>x.id!==t.id));if(templateId===t.id)templateId=null;renderSaved();note('템플릿을 삭제했어요.')}catch(e){note('삭제하지 못했어요. 기존 목록은 유지됩니다.',true)}};row.append(cv,b,del);list.append(row)}}
async function saveTemplate(update){if(busy||!ready)return;const name=$('templateName').value.trim();if(!name){$('templateName').focus();note('템플릿 이름을 입력하세요.',true);return}if(!update&&templates.length>=30){note('템플릿은 최대 30개까지 저장할 수 있어요.',true);return}if(update&&!templateId)return;const id=update?templateId:E.id(),t={id,name,state:E.valid(state)},next=update?templates.map(x=>x.id===id?t:x):[...templates,t];setBusy(true);try{await storeTemplates(next);templateId=id;renderSaved();note(update?'선택한 템플릿을 수정했어요.':'새 템플릿을 저장했어요.')}catch(e){note('저장하지 못했어요: '+e.message+' 기존 목록은 유지됩니다.',true)}finally{setBusy(false)}}
function downloadBlob(b,name){const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000)}
async function exportImage(type){if(busy||!ready)return;try{await document.fonts.ready;E.render($('canvas'),state,images);const title=state.title.replace(/[^\p{L}\p{N}\-_ ]/gu,'').trim()||'one-card';$('canvas').toBlob(b=>{if(b){downloadBlob(b,title+(type==='image/png'?'.png':'.jpg'));note('선택 테두리 없이 완성 이미지를 저장했어요.')}else note('저장에 실패했어요. 다시 시도하세요.',true)},type,.95)}catch(e){note('이미지 저장 실패: '+e.message,true)}}
async function upload(e,replace){const file=e.target.files[0];e.target.value='';if(!file||busy||!ready)return;const target=replace?current():null;if(replace&&(!target||target.type!=='image'||target.locked)){note('잠기지 않은 사진을 먼저 선택하세요.',true);return}if(!replace&&state.layers.length>=40){note('레이어는 최대 40개까지예요.',true);return}setBusy(true);try{if(!['image/png','image/jpeg'].includes(file.type))throw Error('PNG 또는 JPEG 파일만 지원합니다.');if(file.size>10485760)throw Error('10MB 이하의 파일을 선택하세요.');const b=new Uint8Array(await file.slice(0,8).arrayBuffer());if(!(b[0]===137&&b[1]===80&&b[2]===78&&b[3]===71)&&!(b[0]===255&&b[1]===216&&b[2]===255))throw Error('실제 PNG/JPEG 이미지가 아닙니다.');const url=URL.createObjectURL(file);let img;try{img=await decode(url)}finally{URL.revokeObjectURL(url)}const cv=document.createElement('canvas'),scale=Math.min(1,1600/Math.max(img.width,img.height));cv.width=Math.round(img.width*scale);cv.height=Math.round(img.height*scale);cv.getContext('2d').drawImage(img,0,0,cv.width,cv.height);const src=cv.toDataURL(file.type==='image/jpeg'?'image/jpeg':'image/png',.88);if(src.length>4000000)throw Error('이미지 저장 크기가 너무 큽니다. 작은 파일을 사용하세요.');const decoded=await decode(src),old=capture();let next=E.clone(state),newId;if(replace){Object.assign(next.layers.find(n=>n.id===target.id),{src,zoom:1,cropX:50,cropY:50});newId=target.id;}else{const n=E.node('image',{src,w:65,h:45,frame:'polaroid'});next.layers.push(n);newId=n.id;}state=E.valid(next);images[src]=decoded;selected=newId;remember(old);refresh();scheduleDraft();note('사진을 넣었어요. 원본 위치 메타데이터는 저장하지 않습니다.')}catch(e){note(e.message+' 기존 작업은 유지됩니다.',true)}finally{setBusy(false)}}
async function importJson(e){const f=e.target.files[0];e.target.value='';if(!f||busy)return;setBusy(true);try{if(f.size>28000000)throw Error('JSON은 28MB 이내여야 합니다.');const incoming=E.parseBackup(await f.text(),Studio);let im={...images};for(const t of incoming){const next=await prepare(t.state);im={...im,...next};}const map=new Map(templates.map(t=>[t.id,t]));for(const t of incoming)map.set(t.id,t);const next=[...map.values()];if(next.length>30)throw Error('템플릿은 총 30개 이내여야 합니다.');await storeTemplates(next);images=im;renderSaved();note(incoming.length+'개를 가져왔어요. 같은 ID는 백업 내용으로 복원했습니다.')}catch(e){note('가져오기 거부: '+e.message+' 기존 템플릿과 작업은 유지됩니다.',true)}finally{setBusy(false)}}
function exportJson(){downloadBlob(new Blob([JSON.stringify({version:2,templates},null,2)],{type:'application/json'}),'one-card-templates-v2.json');note('템플릿 JSON을 내보냈어요.')}
function point(e){const r=$('overlay').getBoundingClientRect(),[W,H]=E.sizes[state.ratio];return {x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
$('overlay').addEventListener('pointerdown',e=>{if(!ready||busy||e.button!==0)return;const p=point(e),[W,H]=E.sizes[state.ratio],n=current(),before=capture(),scale=$('canvasWrap').clientWidth/W;let mode='move',target=null;if(n&&!n.hidden&&!n.locked){const q=E.localPoint(n,p.x,p.y,W,H),w=W*n.w/100,h=H*n.h/100,t=11/scale;if(Math.hypot(q.x,q.y+h/2+24/scale)<t){mode='rotate';target=n;}else if(Math.abs(Math.abs(q.x)-w/2)<t&&Math.abs(Math.abs(q.y)-h/2)<t){mode='resize';target=n;}}if(!target)target=E.hit(state,p.x,p.y);if(!target){selected=null;refresh(false);return}selected=target.id;drag={mode,before,initial:E.clone(target),start:p,pointer:e.pointerId};$('overlay').setPointerCapture(e.pointerId);$('overlay').focus({preventScroll:true});refresh(false);e.preventDefault()});
$('overlay').addEventListener('pointermove',e=>{if(!drag)return;const p=point(e),n=current(),[W,H]=E.sizes[state.ratio],i=drag.initial;if(!n)return;if(drag.mode==='move'){n.x=Math.max(0,Math.min(100,i.x+(p.x-drag.start.x)/W*100));n.y=Math.max(0,Math.min(100,i.y+(p.y-drag.start.y)/H*100));}else if(drag.mode==='rotate'){let angle=Math.atan2(p.y-H*i.y/100,p.x-W*i.x/100)*180/Math.PI+90;angle=((angle+540)%360)-180;n.rotation=e.shiftKey?Math.round(angle/15)*15:Math.round(angle);}else{const q=E.localPoint(i,p.x,p.y,W,H);n.w=Math.max(2,Math.min(200,Math.abs(q.x)*200/W));n.h=Math.max(1,Math.min(200,Math.abs(q.y)*200/H));if(e.shiftKey){const r=n.w/i.w;n.h=Math.max(1,Math.min(200,i.h*r));}}E.render($('canvas'),state,images);drawOverlay();properties()});
function endDrag(){if(!drag)return;const old=drag.before;drag=null;try{state=E.valid(state);remember(old);refresh();scheduleDraft()}catch(e){state=JSON.parse(old);refresh();note(e.message,true)}}$('overlay').addEventListener('pointerup',endDrag);$('overlay').addEventListener('pointercancel',endDrag);$('overlay').addEventListener('lostpointercapture',endDrag);$('overlay').addEventListener('dblclick',()=>{if(current()?.type==='text'){$('text').focus();$('text').select();if(matchMedia('(max-width:650px)').matches)document.body.classList.toggle('properties-open',true)}});
document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>panel(b.dataset.panel));document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));buildStickers()});$('search').oninput=buildStickers;
document.querySelectorAll('[data-ratio]').forEach(b=>b.onclick=()=>mutate(()=>state.ratio=b.dataset.ratio));document.querySelectorAll('[data-align]').forEach(b=>b.onclick=()=>modify({align:b.dataset.align}));
for(const key of ['text','font','size','color','rotation','opacity','x','y','w','h'])$(key).addEventListener('input',()=>{const n=current();if(!n)return;const v=['text','font','color'].includes(key)?$(key).value:Number($(key).value);const prior=n[key];modify({[key]:v});if(current()?.[key]!==v)$(key).value=prior});for(const [key,prop]of [['imageZoom','zoom'],['cropX','cropX'],['cropY','cropY']])$(key).oninput=()=>modify({[prop]:Number($(key).value)});$('bg').oninput=()=>mutate(()=>state.bg=$('bg').value);$('title').onchange=()=>mutate(()=>state.title=$('title').value.trim()||'이름 없는 한 장');
$('closeAssets').onclick=()=>document.body.classList.toggle('assets-open',false);$('mobileProperties').onclick=()=>document.body.classList.toggle('properties-open',false);$('editSelected').onclick=()=>{document.body.classList.toggle('assets-open',false);document.body.classList.toggle('properties-open',true);if(!matchMedia('(max-width:650px)').matches)$('propertyTitle').scrollIntoView({block:'nearest'});};$('undo').onclick=undo;$('redo').onclick=redo;$('duplicate').onclick=duplicate;$('remove').onclick=remove;$('front').onclick=()=>reorder(99);$('up').onclick=()=>reorder(1);$('down').onclick=()=>reorder(-1);$('lock').onclick=()=>{const n=current();if(n)mutate(()=>n.locked=!n.locked)};
$('addText').onclick=()=>add(E.node('text',{w:70,h:20}));document.querySelectorAll('[data-add-text]').forEach(b=>b.onclick=()=>add(E.node('text',{font:b.dataset.addText,w:74,h:25,text:b.dataset.addText==='hand'?'가볍게 끄적끄적':b.dataset.addText==='serif'?'조금 더 느긋하게':'나만의 한 줄'})));$('addCafe').onclick=()=>add(E.node('image',{w:70,h:49,frame:'polaroid'}));$('upload').onchange=e=>upload(e,false);$('replaceUpload').onchange=e=>upload(e,true);$('download').onclick=()=>exportImage('image/png');$('jpeg').onclick=()=>exportImage('image/jpeg');$('zoomOut').onclick=()=>{viewScale=Math.max(.4,viewScale-.1);fit();drawOverlay()};$('zoomIn').onclick=()=>{viewScale=Math.min(2.5,viewScale+.1);fit();drawOverlay()};$('fit').onclick=()=>{viewScale=1;fit();drawOverlay()};
for(const k of ['openSaved','saveTemplate','backup'])$(k).onclick=openSaved;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('saveNew').onclick=()=>saveTemplate(false);$('updateTemplate').onclick=()=>saveTemplate(true);$('exportJson').onclick=exportJson;$('importJson').onchange=importJson;
document.addEventListener('keydown',e=>{const typing=e.target.closest('input,textarea,select,[contenteditable]');if(typing||$('savedDialog').open||$('confirmDialog').open||busy)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();return}if(e.key==='Escape'){selected=null;refresh(false)}if((e.key==='Delete'||e.key==='Backspace')&&current()){e.preventDefault();remove()}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)&&current()){e.preventDefault();const d=e.shiftKey?1:.1,n=current();modify({x:Math.max(0,Math.min(100,n.x+(e.key==='ArrowLeft'?-d:e.key==='ArrowRight'?d:0))),y:Math.max(0,Math.min(100,n.y+(e.key==='ArrowUp'?-d:e.key==='ArrowDown'?d:0)))});}});
new ResizeObserver(()=>{fit();drawOverlay()}).observe($('stage'));
async function init(){buildTools();buildStickers();setBusy(true);note('사진과 글꼴을 준비하고 있어요.');try{await Promise.all([document.fonts.load('800 84px CardSans'),document.fonts.load('400 84px CardHand'),document.fonts.load('800 84px CardSerif')]);images['assets/cafe.jpg']=await decode('assets/cafe.jpg');try{storeDB=await openDB();const raw=await readDB('templates');if(raw)templates=E.parseBackup(JSON.stringify({version:2,templates:raw}),Studio);else{const v1=localStorage.getItem('one-card-templates-v1');if(v1){templates=E.parseBackup(v1,Studio);await writeDB('templates',templates)}}const draft=await readDB('draft');if(draft){const next=E.valid(draft),im=await prepare(next);state=next;images=im;selected=state.layers.find(n=>n.type==='text')?.id||null;}for(const t of templates)images={...images,...await prepare(t.state)};}catch(e){note('저장된 작업을 읽지 못했어요. 기존 저장 데이터는 유지됩니다. '+e.message,true)}buildPresets();ready=true;refresh();if(!$('status').classList.contains('error'))note('사진과 문구를 고르고, 취향대로 붙여보세요.');}catch(e){ready=true;refresh();note('일부 사진·글꼴을 불러오지 못했어요. 새로고침해 주세요. '+e.message,true)}finally{setBusy(false)}}
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_card_text',description:'선택한 문구 레이어의 텍스트를 변경하고 카드에 반영합니다.',inputSchema:{type:'object',properties:{text:{type:'string',maxLength:2000}},required:['text'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!ready||busy||current()?.type!=='text')throw Error('편집 가능한 문구 레이어를 먼저 선택하세요.');if(typeof input?.text!=='string'||input.text.length>2000)throw Error('문구는 2,000자 이내여야 합니다.');modify({text:input.text});return {text:current().text,ratio:state.ratio}}})).catch(()=>{})}catch{}}
init();
