(function(root){'use strict';
const sizes={'1:1':[1080,1080],'4:5':[1080,1350],'9:16':[1080,1920]},fonts={bold:'CardSans, sans-serif',hand:'CardHand, CardSans, sans-serif',serif:'CardSerif, Georgia, CardSans, serif'},stickers=['spark','star','heart','arrow','tape','ticket','scribble','oval','checker','flower','smile','seal'];
let uid=0;const id=()=>typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():'layer-'+Date.now()+'-'+(++uid);const clone=s=>JSON.parse(JSON.stringify(s));
function node(type,props={}){return {id:id(),type,x:50,y:50,w:28,h:20,rotation:0,opacity:100,hidden:false,locked:false,...(type==='text'?{text:'나만의 한 줄',font:'bold',size:84,color:'#173fd4',effect:'plain',align:'center'}:type==='image'?{src:'assets/cafe.jpg',frame:'torn',zoom:1,cropX:50,cropY:50}:{kind:'spark',color:'#1944e8'}),...props};}
function base(){return {title:'오늘의 작은 행복',ratio:'4:5',bg:'#f6f0e4',pattern:'paper',layers:[]};}
function preset(n=0){const s=base();s.pattern='plain';const add=(t,p)=>s.layers.push(node(t,p));const ink='#262520',orange='#e95b25',cream='#f5efe2';s.bg=cream;
if(n===0){s.title='오늘 좀 좋음';add('image',{x:50,y:61,w:89,h:61,frame:'none'});add('text',{x:48,y:20,w:86,h:28,text:'오늘 좀\n좋음.',size:130,color:orange,align:'left',rotation:-2});add('text',{x:50,y:95,w:88,h:5,text:'GOOD DAYS, LITTLE THINGS.   /   MOOD 01',size:20,color:ink});add('sticker',{kind:'spark',x:85,y:35,w:17,h:13,color:orange,rotation:12});}
else if(n===1){s.title='아무튼 해냄';s.ratio='1:1';s.bg=ink;add('text',{x:49,y:40,w:85,h:56,text:'아무튼,\n해냄.',size:155,color:cream,align:'left'});add('sticker',{kind:'seal',x:80,y:79,w:27,h:27,color:orange,rotation:13});add('text',{x:32,y:85,w:49,h:12,text:'잘했어. 진짜로.',font:'hand',size:51,color:cream,align:'left'});}
else if(n===2){s.title='지금은 충전 중';s.bg='#e8ece4';s.ratio='9:16';add('image',{x:50,y:61,w:76,h:43,frame:'rounded'});add('text',{x:49,y:19,w:80,h:17,text:'지금은\n충전 중',font:'serif',size:98,color:'#3e5745',align:'left'});add('text',{x:48,y:34,w:77,h:7,text:'잠깐, 내 속도로.',font:'hand',size:47,color:'#3e5745',align:'left'});add('text',{x:50,y:89,w:80,h:6,text:'TAKE YOUR TIME',font:'serif',size:25,color:'#3e5745'});}
else if(n===3){s.title='별일 없는 날';s.bg='#f3eee6';add('image',{x:50,y:57,w:79,h:58,frame:'polaroid',rotation:-3});add('text',{x:48,y:14,w:82,h:15,text:'별일 없는 날',font:'serif',size:83,color:ink,align:'left'});add('text',{x:50,y:90,w:85,h:9,text:'이런 하루도, 꽤 괜찮아.',font:'hand',size:42,color:ink});add('text',{x:49,y:23,w:82,h:5,text:'ORDINARY DAYS / EXTRAORDINARY MOMENTS',size:17,color:'#756c61',align:'left'});}
else if(n===4){s.title='이건 저장각';s.bg=orange;add('image',{x:50,y:60,w:90,h:67,frame:'none'});add('text',{x:50,y:16,w:92,h:24,text:'이건 저장각',size:123,color:cream});add('text',{x:31,y:91,w:46,h:8,text:'SAVE THIS MOOD.',size:24,color:cream,effect:'shadow',align:'left'});add('sticker',{kind:'oval',x:82,y:87,w:22,h:14,color:cream,rotation:-20});}
else{s.title='말로는 부족해서';s.bg='#f7eee6';s.pattern='paper';add('text',{x:47,y:31,w:82,h:28,text:'말로는\n부족해서.',font:'serif',size:96,color:ink,align:'left'});add('sticker',{kind:'heart',x:66,y:65,w:37,h:30,color:'#c93d32',rotation:-12});add('text',{x:45,y:86,w:77,h:12,text:'이 한 장에 마음을 담아.',font:'hand',size:48,color:ink,rotation:-5,align:'left'});add('text',{x:48,y:12,w:81,h:5,text:'A LITTLE NOTE FOR YOU',size:21,color:'#9a7b64',align:'left'});}return s;}

function valid(s){if(!s||!sizes[s.ratio]||typeof s.title!=='string'||s.title.length>60||!/^#[0-9a-f]{6}$/i.test(s.bg)||!['paper','plain','grid','dots','checker'].includes(s.pattern)||!Array.isArray(s.layers)||s.layers.length>40)throw Error('카드 필수 항목 또는 형식이 올바르지 않습니다.');const ids=new Set;for(const n of s.layers){if(!n||!['text','image','sticker'].includes(n.type)||typeof n.id!=='string'||!n.id||n.id.length>100||ids.has(n.id))throw Error('레이어 ID와 종류를 확인하세요.');ids.add(n.id);for(const [k,min,max]of [['x',0,100],['y',0,100],['w',2,200],['h',1,200],['rotation',-180,180],['opacity',0,100]])if(typeof n[k]!=='number'||!Number.isFinite(n[k])||n[k]<min||n[k]>max)throw Error('레이어 값이 범위를 벗어났습니다: '+k);if(typeof n.hidden!=='boolean'||typeof n.locked!=='boolean')throw Error('레이어 표시·잠금 값이 필요합니다.');if(n.type!=='image'&&!/^#[0-9a-f]{6}$/i.test(n.color))throw Error('색상 형식 오류');if(n.type==='text'){if(typeof n.text!=='string'||n.text.length>2000||!fonts[n.font]||!['plain','outline','shadow','label'].includes(n.effect)||!['left','center','right'].includes(n.align)||!Number.isFinite(n.size)||n.size<12||n.size>200)throw Error('문구는 2,000자 이내이며 올바른 스타일 값이 필요합니다.');}if(n.type==='sticker'&&!stickers.includes(n.kind))throw Error('지원하지 않는 스티커입니다.');if(n.type==='image'){if(typeof n.src!=='string'||n.src.length>4000000||!(n.src==='assets/cafe.jpg'||/^data:image\/(png|jpeg);base64,[A-Za-z0-9+/=]+$/.test(n.src))||!['none','rounded','torn','polaroid'].includes(n.frame))throw Error('이미지 데이터나 프레임을 확인하세요.');for(const [k,a,b]of [['zoom',1,3],['cropX',0,100],['cropY',0,100]])if(!Number.isFinite(n[k])||n[k]<a||n[k]>b)throw Error('이미지 위치 값 오류');}}return clone(s);}
function migrate(o){const s=base();s.title='이전 버전 템플릿';s.ratio=o.ratio;s.bg=o.bg;s.pattern='plain';if(o.image)s.layers.push(node('image',{src:o.image,frame:'none',w:100,h:100,x:50,y:50,zoom:o.zoom,cropX:o.ix,cropY:o.iy}));s.layers.push(node('text',{text:o.text,size:o.size,color:o.color,align:o.align,x:o.x,y:o.y,w:80,h:70}));return valid(s);}
function parseBackup(raw,legacy){let o;try{o=JSON.parse(raw)}catch{throw Error('JSON 문법이 손상되었습니다.');}if(!o||![1,2].includes(o.version)||!Array.isArray(o.templates)||o.templates.length>30)throw Error('version 또는 templates 항목이 올바르지 않습니다.');if(o.version===1){if(!legacy)throw Error('이전 버전 검증기를 사용할 수 없습니다.');return legacy.parseBackup(raw).map(t=>({...t,state:migrate(t.state)}));}const ids=new Set;return o.templates.map(t=>{if(typeof t?.id!=='string'||!t.id||ids.has(t.id)||typeof t.name!=='string'||!t.name.trim()||t.name.length>60)throw Error('템플릿 이름·ID 오류');ids.add(t.id);return {id:t.id,name:t.name,state:valid(t.state)};});}
function wrap(c,text,width){const sg=new Intl.Segmenter('ko',{granularity:'grapheme'});return text.split('\n').flatMap(l=>{const out=[];let row='';for(const {segment:g}of sg.segment(l)){if(row&&c.measureText(row+g).width>width){out.push(row);row=g;}else row+=g;}out.push(row);return out;});}
function textLayout(c,n,w,h){const family=fonts[n.font];let size=n.size;const measure=z=>{c.font=`${n.font==='hand'?400:800} ${z}px ${family}`;return wrap(c,n.text,Math.max(5,w-24));};let lines=measure(size);if(lines.length*size*1.2>h-20||lines.some(l=>c.measureText(l).width>w-24)){let a=.05,b=size;for(let i=0;i<12;i++){const mid=(a+b)/2,ls=measure(mid);if(ls.length*mid*1.2<=Math.max(1,h-20)&&ls.every(l=>c.measureText(l).width<=Math.max(5,w-24)))a=mid;else b=mid;}size=a;lines=measure(size);}return {size,lines};}
function pathStar(c,w,h,points=5,inner=.45){c.beginPath();for(let i=0;i<points*2;i++){let a=-Math.PI/2+i*Math.PI/points,r=i%2?inner:1;c.lineTo(Math.cos(a)*w/2*r,Math.sin(a)*h/2*r);}c.closePath();}
function sticker(c,n,w,h){const col=n.color;c.fillStyle=col;c.strokeStyle=col;c.lineWidth=Math.max(3,Math.min(w,h)*.045);c.lineCap='round';c.lineJoin='round';switch(n.kind){case 'star':pathStar(c,w,h);c.fill();break;case 'spark':pathStar(c,w,h,4,.22);c.fill();break;case 'heart':c.beginPath();c.moveTo(0,h*.38);c.bezierCurveTo(-w*.95,-h*.15,-w*.34,-h*.72,0,-h*.18);c.bezierCurveTo(w*.34,-h*.72,w*.95,-h*.15,0,h*.38);c.stroke();break;case 'arrow':c.beginPath();c.moveTo(-w*.42,h*.36);c.bezierCurveTo(-w*.28,-h*.4,w*.09,-h*.32,-w*.03,h*.08);c.bezierCurveTo(-w*.14,h*.38,-w*.39,-h*.04,w*.42,-h*.13);c.moveTo(w*.19,-h*.34);c.lineTo(w*.44,-h*.14);c.lineTo(w*.27,h*.12);c.stroke();break;case 'tape':c.beginPath();for(let i=0;i<8;i++)c.lineTo(-w/2+(i%2?6:0),-h/2+i*h/7);c.lineTo(w/2,h/2);for(let i=0;i<8;i++)c.lineTo(w/2-(i%2?6:0),h/2-i*h/7);c.closePath();c.fill();c.strokeStyle='#ffffff33';c.lineWidth=1;for(let i=-w/2;i<w/2;i+=12){c.beginPath();c.moveTo(i,-h/2);c.lineTo(i+20,h/2);c.stroke();}break;case 'ticket':c.fillRect(-w/2,-h/2,w,h);c.strokeStyle='#00000035';c.setLineDash([4,6]);c.strokeRect(-w*.43,-h*.42,w*.86,h*.84);c.setLineDash([]);c.fillStyle='#282820';c.font=`${Math.min(w*.14,h*.17)}px CardSerif`;c.textAlign='center';c.fillText('GOOD',0,-h*.13);c.fillText('THINGS',0,h*.07);c.fillText('AHEAD',0,h*.27);break;case 'scribble':c.beginPath();c.moveTo(-w*.45,h*.15);c.bezierCurveTo(-w*.2,-h*.13,w*.03,-h*.25,w*.42,-h*.15);c.moveTo(-w*.3,h*.4);c.lineTo(w*.3,h*.14);c.stroke();break;case 'oval':c.beginPath();c.ellipse(0,0,w*.45,h*.4,-.1,0,Math.PI*2);c.stroke();break;case 'checker':for(let x=0;x<6;x++)for(let y=0;y<3;y++){c.fillStyle=(x+y)%2?col:'#fffaf0';c.fillRect(-w/2+x*w/6,-h/2+y*h/3,w/6+1,h/3+1);}break;case 'flower':for(let i=0;i<8;i++){c.save();c.rotate(i*Math.PI/4);c.beginPath();c.ellipse(0,-h*.26,w*.12,h*.24,0,0,Math.PI*2);c.fill();c.restore();}c.fillStyle='#f8efe0';c.beginPath();c.ellipse(0,0,w*.17,h*.17,0,0,Math.PI*2);c.fill();break;case 'smile':c.beginPath();c.ellipse(0,0,w*.45,h*.45,0,0,Math.PI*2);c.fill();c.strokeStyle='#282820';c.lineWidth=Math.min(w,h)*.035;c.beginPath();c.ellipse(0,0,w*.25,h*.25,0,.15,Math.PI-.15);c.stroke();c.fillStyle='#282820';for(let dx of [-.16,.16]){c.beginPath();c.ellipse(w*dx,-h*.13,w*.03,h*.065,0,0,Math.PI*2);c.fill();}break;case 'seal':pathStar(c,w,h,14,.88);c.fill();c.fillStyle='#292820';c.font=`${Math.min(w*.16,h*.2)}px CardSerif`;c.textAlign='center';c.fillText('SLOW',0,-h*.05);c.fillText('MOMENTS',0,h*.18);break;}}
const grainCache=new WeakMap();
function render(canvas,s,images={},opts={}){let [W,H]=sizes[s.ratio];if(canvas.width!==W)canvas.width=W;if(canvas.height!==H)canvas.height=H;const c=canvas.getContext('2d');c.clearRect(0,0,W,H);c.fillStyle=s.bg;c.fillRect(0,0,W,H);c.save();c.strokeStyle='#25304313';c.fillStyle='#25304320';c.lineWidth=1;if(s.pattern==='grid'){for(let a=0;a<W;a+=45){c.beginPath();c.moveTo(a,0);c.lineTo(a,H);c.stroke();}for(let a=0;a<H;a+=45){c.beginPath();c.moveTo(0,a);c.lineTo(W,a);c.stroke();}}if(s.pattern==='dots')for(let a=18;a<W;a+=35)for(let b=18;b<H;b+=35){c.beginPath();c.arc(a,b,1.3,0,7);c.fill();}if(s.pattern==='checker'){c.fillStyle='#ffffff50';for(let a=0;a<W/70;a++)for(let b=0;b<H/70;b++)if((a+b)%2)c.fillRect(a*70,b*70,70,70);}if(s.pattern==='paper'){let grain=grainCache.get(canvas);if(!grain||grain.W!==W||grain.H!==H){let seed=12345,points=[];for(let i=0;i<18000;i++){seed=(seed*16807)%2147483647;let x=seed%W;seed=(seed*16807)%2147483647;points.push([x,seed%H]);}grain={W,H,points};grainCache.set(canvas,grain);}c.fillStyle='#493b2520';for(const [x,y]of grain.points)c.fillRect(x,y,1.2,1.2);}c.restore();const layouts={};for(const n of s.layers){if(n.hidden)continue;const w=W*n.w/100,h=H*n.h/100;c.save();c.translate(W*n.x/100,H*n.y/100);c.rotate(n.rotation*Math.PI/180);c.globalAlpha=n.opacity/100;if(n.type==='sticker')sticker(c,n,w,h);if(n.type==='text'){const lay=textLayout(c,n,w,h);layouts[n.id]=lay;const pad=12,xx=n.align==='left'?-w/2+pad:n.align==='right'?w/2-pad:0,yy=-lay.lines.length*lay.size*1.2/2;c.textBaseline='top';c.textAlign=n.align;if(n.effect==='label'){c.fillStyle='#fffaf0';c.fillRect(-w/2,-h/2,w,h);}c.fillStyle=n.color;c.strokeStyle=n.color;if(n.effect==='shadow'){c.shadowColor='#00000045';c.shadowBlur=2;c.shadowOffsetX=6;c.shadowOffsetY=7;}for(let i=0;i<lay.lines.length;i++){if(n.effect==='outline'){c.lineWidth=Math.max(1,lay.size*.018);c.strokeText(lay.lines[i],xx,yy+i*lay.size*1.2);}else c.fillText(lay.lines[i],xx,yy+i*lay.size*1.2);}}if(n.type==='image'){const im=images[n.src];let iw=w,ih=h,top=-h/2;if(n.frame==='polaroid'){c.shadowColor='#0000001c';c.shadowBlur=18;c.shadowOffsetY=6;c.fillStyle='#fffdf8';c.fillRect(-w/2,-h/2,w,h);c.shadowColor='transparent';iw=w*.9;ih=h*.81;top=-h/2+w*.05;}c.beginPath();if(n.frame==='torn'){for(let i=0;i<=30;i++)c.lineTo(-w/2+i*w/30,-h/2+(Math.sin(i*3.71)*.5+.5)*12);for(let i=0;i<=30;i++)c.lineTo(w/2-(Math.sin(i*5.3)*.5+.5)*8,-h/2+i*h/30);for(let i=30;i>=0;i--)c.lineTo(-w/2+i*w/30,h/2-(Math.sin(i*4.13)*.5+.5)*14);for(let i=30;i>=0;i--)c.lineTo(-w/2+(Math.sin(i*4.7)*.5+.5)*8,-h/2+i*h/30);c.closePath();}else if(n.frame==='rounded')c.roundRect(-iw/2,top,iw,ih,30);else c.rect(-iw/2,top,iw,ih);c.clip();if(im){const scale=Math.max(iw/im.width,ih/im.height)*n.zoom,dw=im.width*scale,dh=im.height*scale;c.drawImage(im,-iw/2+(iw-dw)*n.cropX/100,top+(ih-dh)*n.cropY/100,dw,dh);}else{c.fillStyle='#d6dcdf';c.fillRect(-iw/2,top,iw,ih);}}c.restore();}return layouts;}
function localPoint(n,px,py,W,H){const rad=-n.rotation*Math.PI/180,dx=px-W*n.x/100,dy=py-H*n.y/100;return {x:dx*Math.cos(rad)-dy*Math.sin(rad),y:dx*Math.sin(rad)+dy*Math.cos(rad)};}
function hit(s,px,py){const [W,H]=sizes[s.ratio];return [...s.layers].reverse().find(n=>{if(n.hidden||n.locked)return false;const p=localPoint(n,px,py,W,H);return Math.abs(p.x)<=W*n.w/200&&Math.abs(p.y)<=H*n.h/200;});}
root.Scrap={sizes,fonts,stickers,id,clone,node,base,preset,valid,migrate,parseBackup,wrap,textLayout,sticker,render,localPoint,hit};if(typeof module!=='undefined')module.exports=root.Scrap;
})(typeof window!=='undefined'?window:globalThis);
