'use strict';
const $=id=>document.getElementById(id),KEY='one-card-templates-v1';let state=Studio.initial(),picture=null,templates=[],selected=null,busy=false;
const notify=(t,error=false)=>{$('status').textContent=t;$('status').classList.toggle('error',error)};
const presets=[{text:'오늘 할 일\n일단, 한 입.',ratio:'1:1',theme:'blue',bg:'#315bdf'},{text:'별일 없어도\n네 편이야.',ratio:'4:5',theme:'pink',bg:'#ad4878'},{text:'작게 시작해도\n시작은 시작.',ratio:'9:16',theme:'green',bg:'#287768'}];
const fields=['text','size','color','bg','x','y','align','zoom','ix','iy','shade'];
function draw(){Studio.render($('canvas'),state,picture);$('dimensions').textContent=Studio.sizes[state.ratio].join(' × ');$('count').textContent=state.text.length+' / 2,000';$('sizeValue').textContent=state.size;document.querySelectorAll('[data-ratio]').forEach(e=>{e.classList.toggle('active',e.dataset.ratio===state.ratio);e.setAttribute('aria-pressed',e.dataset.ratio===state.ratio)});document.querySelectorAll('[data-theme]').forEach(e=>e.classList.toggle('active',e.dataset.theme===state.theme));}
function sync(){fields.forEach(k=>$(k).value=state[k]);draw()}
function commit(next){try{const raw=JSON.stringify({version:1,templates:next});if(raw.length>4000000)throw Error('저장 용량을 초과했습니다. 이미지를 줄이거나 템플릿을 정리하세요.');localStorage.setItem(KEY,raw);templates=next;list();return true}catch(e){notify('저장하지 못했습니다. 기존 목록은 유지됩니다. '+e.message,true);return false}}
function list(){const el=$('templates');el.replaceChildren();$('total').textContent=templates.length+'개';$('update').disabled=!selected; if(!templates.length){const p=document.createElement('p');p.className='empty';p.textContent='마음에 드는 한 장을 저장해 두세요.';el.append(p)}for(const t of templates){const row=document.createElement('div');row.className='template'+(t.id===selected?' selected':'');const b=document.createElement('button');b.textContent=t.name;const sm=document.createElement('small');sm.textContent=t.state.ratio+' · 불러오기';b.append(sm);b.onclick=()=>loadTemplate(t);const del=document.createElement('button');del.textContent='삭제';del.setAttribute('aria-label',t.name+' 삭제');del.onclick=()=>{if(!confirm('“'+t.name+'” 템플릿을 삭제할까요?'))return;if(commit(templates.filter(v=>v.id!==t.id))){if(selected===t.id)selected=null;list();notify('템플릿을 삭제했습니다. 현재 편집 내용은 유지됩니다.')}};row.append(b,del);el.append(row)}}
async function decode(src){const img=new Image();img.src=src;await img.decode();if(!img.width||!img.height||img.width*img.height>20000000)throw Error('이미지는 2,000만 화소 이내여야 합니다.');return img}
async function loadTemplate(t){if(busy)return;busy=true;try{const n=Studio.valid(t.state),im=n.image?await decode(n.image):null;state=n;picture=im;selected=t.id;$('name').value=t.name;sync();list();notify('“'+t.name+'”을 불러왔습니다.')}catch(e){notify('불러오지 못했습니다. 기존 작업은 유지됩니다. '+e.message,true)}finally{busy=false}}
fields.forEach(k=>$(k).addEventListener('input',()=>{if(busy){$(k).value=state[k];return}const value=['text','color','bg','align'].includes(k)?$(k).value:Number($(k).value);try{const n=Studio.valid({...state,[k]:value});state=n;draw()}catch(e){$(k).value=state[k];notify(e.message+' 기존 작업은 유지됩니다.',true)}}));
document.querySelectorAll('[data-ratio]').forEach(b=>b.onclick=()=>{if(busy)return;state.ratio=b.dataset.ratio;draw()});document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{if(busy)return;state.theme=b.dataset.theme;state.bg={blue:'#315bdf',pink:'#ad4878',green:'#287768',plain:'#f0a53c'}[state.theme];sync()});document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{if(busy)return;if(state.image||state.text!==Studio.initial().text){if(!confirm('현재 편집 내용을 예시 카드로 바꿀까요? 저장한 템플릿은 유지됩니다.'))return}state={...Studio.initial(),...presets[Number(b.dataset.preset)]};picture=null;selected=null;sync();list();notify('예시를 불러왔습니다. 문구를 자유롭게 바꿔보세요.')});
$('upload').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f||busy)return;busy=true;try{if(!['image/png','image/jpeg'].includes(f.type))throw Error('PNG 또는 JPEG 파일만 지원합니다.');if(f.size>10485760)throw Error('10MB 이하의 파일을 선택하세요.');const bytes=new Uint8Array(await f.slice(0,8).arrayBuffer());if(!(bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71)&&!(bytes[0]===255&&bytes[1]===216&&bytes[2]===255))throw Error('실제 PNG/JPEG 이미지가 아닙니다.');const url=URL.createObjectURL(f);let img;try{img=await decode(url)}finally{URL.revokeObjectURL(url)}const c=document.createElement('canvas'),scale=Math.min(1,1600/Math.max(img.width,img.height));c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);const clean=c.toDataURL(f.type==='image/jpeg'?'image/jpeg':'image/png',.9),im=await decode(clean);state={...state,image:clean,zoom:1,ix:50,iy:50};picture=im;sync();notify('이미지를 불러왔습니다. 원본 위치 메타데이터는 저장하지 않습니다.')}catch(e){notify(e.message+' 기존 작업은 유지됩니다.',true)}finally{busy=false}};
$('removeImage').onclick=()=>{if(busy)return;state.image=null;picture=null;draw();notify('이미지를 제거했습니다.')};
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}
async function exportImage(type){if(busy)return;await document.fonts.ready;draw();$('canvas').toBlob(b=>{if(b){download(b,'one-card-'+state.ratio.replace(':','x')+(type==='image/png'?'.png':'.jpg'));notify('미리보기와 같은 이미지로 저장했습니다.')}else notify('이미지 저장에 실패했습니다. 다시 시도하세요.',true)},type,.95)}
$('download').onclick=()=>exportImage('image/png');$('jpeg').onclick=()=>exportImage('image/jpeg');
function templateSave(update){if(busy)return;const name=$('name').value.trim();if(!name){notify('템플릿 이름을 입력하세요.',true);$('name').focus();return}if(!update&&templates.length>=30){notify('템플릿은 최대 30개까지 저장할 수 있습니다.',true);return}if(update&&!selected)return;const id=update?selected:crypto.randomUUID();const entry={id,name,state:Studio.valid(state)},next=update?templates.map(t=>t.id===id?entry:t):[...templates,entry];if(commit(next)){selected=id;list();notify(update?'선택한 템플릿을 수정했습니다.':'새 템플릿을 저장했습니다.')}}
$('save').onclick=()=>templateSave(false);$('update').onclick=()=>templateSave(true);$('export').onclick=()=>{download(new Blob([JSON.stringify({version:1,templates},null,2)],{type:'application/json'}),'one-card-templates.json');notify('템플릿 JSON을 내보냈습니다.')};
$('import').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f||busy)return;busy=true;try{if(f.size>6000000)throw Error('JSON은 6MB 이내여야 합니다.');const incoming=Studio.parseBackup(await f.text());for(const t of incoming)if(t.state.image)await decode(t.state.image);const map=new Map(templates.map(t=>[t.id,t]));for(const t of incoming)map.set(t.id,t);const next=[...map.values()];if(next.length>30)throw Error('가져오기 후 템플릿은 30개 이내여야 합니다.');if(commit(next))notify(incoming.length+'개 템플릿을 가져왔습니다. 같은 ID의 템플릿은 백업 내용으로 복원됩니다.')}catch(e){notify('가져오기 거부: '+e.message+' 기존 템플릿과 편집 내용은 유지됩니다.',true)}finally{busy=false}};
try{const raw=localStorage.getItem(KEY);if(raw)templates=Studio.parseBackup(raw)}catch(e){notify('저장된 템플릿을 읽지 못했습니다. 원본 저장 데이터는 변경하지 않았습니다.',true)}sync();list();document.fonts.ready.then(draw);
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_card_text',description:'현재 카드 문구를 변경하고 미리보기를 갱신합니다.',inputSchema:{type:'object',properties:{text:{type:'string',maxLength:2000}},required:['text'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(busy)throw Error('파일 처리가 끝난 뒤 다시 시도하세요.');if(typeof input?.text!=='string')throw Error('문구가 필요합니다.');state=Studio.valid({...state,text:input.text});sync();return {text:state.text,ratio:state.ratio}}})).catch(()=>{})}catch{}}
