(function(root){
'use strict';
const sizes={'1:1':[1080,1080],'4:5':[1080,1350],'9:16':[1080,1920]};
const initial=()=>({ratio:'1:1',text:'오늘 할 일\n일단, 한 입.',size:92,color:'#ffffff',bg:'#315bdf',x:50,y:53,align:'center',theme:'blue',image:null,zoom:1,ix:50,iy:50,shade:20});
function valid(s){if(!s||typeof s!=='object'||!sizes[s.ratio]||typeof s.text!=='string'||s.text.length>2000)throw Error('문구는 2,000자 이내, 비율은 1:1·4:5·9:16이어야 합니다.');for(const [k,a,b]of [['size',24,180],['x',10,90],['y',10,90],['zoom',1,3],['ix',0,100],['iy',0,100],['shade',0,80]])if(typeof s[k]!=='number'||!Number.isFinite(s[k])||s[k]<a||s[k]>b)throw Error('필수 편집 값이 없거나 범위를 벗어났습니다: '+k);for(const k of ['color','bg'])if(!/^#[0-9a-f]{6}$/i.test(s[k]))throw Error('색상 형식이 올바르지 않습니다.');if(!['left','center','right'].includes(s.align)||!['blue','pink','green','plain'].includes(s.theme))throw Error('필수 스타일이 올바르지 않습니다.');if(s.image!==null&&(typeof s.image!=='string'||!/^data:image\/(png|jpeg);base64,[A-Za-z0-9+/=]+$/.test(s.image)||s.image.length>16000000))throw Error('이미지 데이터가 올바르지 않습니다.');return JSON.parse(JSON.stringify(s));}
function parseBackup(t){const o=JSON.parse(t);if(o?.version!==1||!Array.isArray(o.templates)||o.templates.length>30)throw Error('version 또는 templates 필수 항목을 확인하세요.');const ids=new Set;return o.templates.map(a=>{if(!a||typeof a.id!=='string'||!a.id||ids.has(a.id)||typeof a.name!=='string'||!a.name.trim()||a.name.length>60)throw Error('템플릿 ID 또는 이름이 올바르지 않습니다.');ids.add(a.id);return {id:a.id,name:a.name,state:valid(a.state)};});}
function wrap(ctx,text,width){const seg=typeof Intl.Segmenter==='function'?new Intl.Segmenter('ko',{granularity:'grapheme'}):null;return text.split('\n').flatMap(line=>{const chars=seg?Array.from(seg.segment(line),x=>x.segment):Array.from(line),out=[];let row='';for(const ch of chars){if(row&&ctx.measureText(row+ch).width>width){out.push(row);row=ch;}else row+=ch;}out.push(row);return out;});}
function render(canvas,s,img){const [w,h]=sizes[s.ratio];canvas.width=w;canvas.height=h;const c=canvas.getContext('2d');c.fillStyle=s.bg;c.fillRect(0,0,w,h);if(!img&&s.theme!=='plain'){const g=c.createLinearGradient(0,0,w,h);g.addColorStop(0,s.bg);g.addColorStop(1,s.theme==='pink'?'#6c2b59':s.theme==='green'?'#123e3a':'#192961');c.fillStyle=g;c.fillRect(0,0,w,h);c.strokeStyle='#ffffff22';c.lineWidth=2;for(let i=-h;i<w+h;i+=95){c.beginPath();c.moveTo(i,0);c.lineTo(i+h,h);c.stroke();}c.fillStyle='#ffffff18';c.beginPath();c.arc(w*.8,h*.2,w*.42,0,Math.PI*2);c.fill();}if(img){const r=Math.max(w/img.width,h/img.height)*s.zoom,dw=img.width*r,dh=img.height*r;c.drawImage(img,(w-dw)*s.ix/100,(h-dh)*s.iy/100,dw,dh);c.fillStyle=`rgba(0,0,0,${s.shade/100})`;c.fillRect(0,0,w,h);}const anchor=w*s.x/100;const usable=s.align==='center'?2*Math.min(anchor-50,w-50-anchor):s.align==='left'?w-50-anchor:anchor-50;let fs=s.size,lines=[];const font=n=>`800 ${n}px CardSans, "Noto Sans CJK KR", "Malgun Gothic", sans-serif`;c.font=font(fs);lines=wrap(c,s.text,Math.max(40,usable));if(lines.length*fs*1.28>h-120){let lo=.1,hi=fs;for(let step=0;step<12;step++){const mid=(lo+hi)/2;c.font=font(mid);const test=wrap(c,s.text,Math.max(40,usable));if(test.length*mid*1.28<=h-120)lo=mid;else hi=mid;}fs=lo;c.font=font(fs);lines=wrap(c,s.text,Math.max(40,usable));}let top=Math.max(60,Math.min(h-60-lines.length*fs*1.28,h*s.y/100-lines.length*fs*1.28/2));c.textBaseline='top';c.textAlign=s.align;c.fillStyle=s.color;c.shadowColor='#00000040';c.shadowBlur=img?8:0;lines.forEach((t,i)=>c.fillText(t,anchor,top+i*fs*1.28));return {lines,fontSize:fs,top,maxWidth:usable,width:w,height:h};}
root.Studio={sizes,initial,valid,parseBackup,wrap,render};if(typeof module!=='undefined')module.exports=root.Studio;
})(typeof window!=='undefined'?window:globalThis);
